package com.VideoInfo.dao;

import android.database.sqlite.SQLiteDatabase;

import com.VideoInfo.entity.FileFolder;
import com.VideoInfo.entity.UserInfo;
import com.VideoInfo.entity.VideoInfo;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig videoInfoDaoConfig;
    private final DaoConfig fileFolderDaoConfig;
    private final DaoConfig userInfoDaoConfig;

    private final VideoInfoDao videoInfoDao;
    private final FileFolderDao fileFolderDao;
    private final UserInfoDao userInfoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        videoInfoDaoConfig = daoConfigMap.get(VideoInfoDao.class).clone();
        videoInfoDaoConfig.initIdentityScope(type);

        fileFolderDaoConfig = daoConfigMap.get(FileFolderDao.class).clone();
        fileFolderDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        videoInfoDao = new VideoInfoDao(videoInfoDaoConfig, this);
        fileFolderDao = new FileFolderDao(fileFolderDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);

        registerDao(VideoInfo.class, videoInfoDao);
        registerDao(FileFolder.class, fileFolderDao);
        registerDao(UserInfo.class, userInfoDao);
    }
    
    public void clear() {
        videoInfoDaoConfig.getIdentityScope().clear();
        fileFolderDaoConfig.getIdentityScope().clear();
        userInfoDaoConfig.getIdentityScope().clear();
    }

    public VideoInfoDao getVideoInfoDao() {
        return videoInfoDao;
    }

    public FileFolderDao getFileFolderDao() {
        return fileFolderDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

}
